name: lihuowang
channels:
  - defaults
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2024.12.31
  - libffi=3.4.4
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.11.11
  - readline=8.2
  - setuptools=75.1.0
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - attrs==24.3.0
      - certifi==2024.12.14
      - charset-normalizer==3.4.1
      - datasets==3.2.0
      - dill==0.3.8
      - filelock==3.16.1
      - frozenlist==1.5.0
      - fsspec==2024.9.0
      - huggingface-hub==0.27.1
      - idna==3.10
      - multidict==6.1.0
      - multiprocess==0.70.16
      - numpy==2.2.1
      - packaging==24.2
      - pandas==2.2.3
      - propcache==0.2.1
      - pyarrow==18.1.0
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - pytz==2024.2
      - pyyaml==6.0.2
      - requests==2.32.3
      - six==1.17.0
      - tqdm==4.67.1
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - urllib3==2.3.0
      - xxhash==3.5.0
      - yarl==1.18.3
